package entity;
// Generated 19/05/2017 05:19:01 PM by Hibernate Tools 4.3.1



/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private int idAdministrador;
     private TipoAdministrador tipoAdministrador;
     private String usuario;
     private String contrasena;
     private String correo;

    public Administrador() {
    }

    public Administrador(int idAdministrador, TipoAdministrador tipoAdministrador, String usuario, String contrasena, String correo) {
       this.idAdministrador = idAdministrador;
       this.tipoAdministrador = tipoAdministrador;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.correo = correo;
    }
   
    public int getIdAdministrador() {
        return this.idAdministrador;
    }
    
    public void setIdAdministrador(int idAdministrador) {
        this.idAdministrador = idAdministrador;
    }
    public TipoAdministrador getTipoAdministrador() {
        return this.tipoAdministrador;
    }
    
    public void setTipoAdministrador(TipoAdministrador tipoAdministrador) {
        this.tipoAdministrador = tipoAdministrador;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }




}


