package entity;
// Generated 19/05/2017 05:19:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Aspirante generated by hbm2java
 */
public class Aspirante  implements java.io.Serializable {


     private String claveAspirante;
     private Congreso congreso;
     private int idAspirante;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String calle;
     private String numero;
     private String colonia;
     private Integer cp;
     private String telefono;
     private String celular;
     private String correo;
     private String procedencia;
     private String otros;
     private Integer consecutivo;
     private boolean activo;
     private Boolean factura;
     private BigDecimal pagar;
     private Date fechaRegistro;
     private Integer idTema;
     private int idProfesion;
     private int idMunicipio;
     private int idCategoria;
     private String folio;
     private Boolean asistio;
     private Set facturas = new HashSet(0);

    public Aspirante() {
    }

	
    public Aspirante(String claveAspirante, Congreso congreso, int idAspirante, String nombre, String correo, boolean activo, BigDecimal pagar, Date fechaRegistro, int idProfesion, int idMunicipio, int idCategoria) {
        this.claveAspirante = claveAspirante;
        this.congreso = congreso;
        this.idAspirante = idAspirante;
        this.nombre = nombre;
        this.correo = correo;
        this.activo = activo;
        this.pagar = pagar;
        this.fechaRegistro = fechaRegistro;
        this.idProfesion = idProfesion;
        this.idMunicipio = idMunicipio;
        this.idCategoria = idCategoria;
    }
    public Aspirante(String claveAspirante, Congreso congreso, int idAspirante, String nombre, String apellidoPaterno, String apellidoMaterno, String calle, String numero, String colonia, Integer cp, String telefono, String celular, String correo, String procedencia, String otros, Integer consecutivo, boolean activo, Boolean factura, BigDecimal pagar, Date fechaRegistro, Integer idTema, int idProfesion, int idMunicipio, int idCategoria, String folio, Boolean asistio, Set facturas) {
       this.claveAspirante = claveAspirante;
       this.congreso = congreso;
       this.idAspirante = idAspirante;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.calle = calle;
       this.numero = numero;
       this.colonia = colonia;
       this.cp = cp;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
       this.procedencia = procedencia;
       this.otros = otros;
       this.consecutivo = consecutivo;
       this.activo = activo;
       this.factura = factura;
       this.pagar = pagar;
       this.fechaRegistro = fechaRegistro;
       this.idTema = idTema;
       this.idProfesion = idProfesion;
       this.idMunicipio = idMunicipio;
       this.idCategoria = idCategoria;
       this.folio = folio;
       this.asistio = asistio;
       this.facturas = facturas;
    }
   
    public String getClaveAspirante() {
        return this.claveAspirante;
    }
    
    public void setClaveAspirante(String claveAspirante) {
        this.claveAspirante = claveAspirante;
    }
    public Congreso getCongreso() {
        return this.congreso;
    }
    
    public void setCongreso(Congreso congreso) {
        this.congreso = congreso;
    }
    public int getIdAspirante() {
        return this.idAspirante;
    }
    
    public void setIdAspirante(int idAspirante) {
        this.idAspirante = idAspirante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public Integer getCp() {
        return this.cp;
    }
    
    public void setCp(Integer cp) {
        this.cp = cp;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getProcedencia() {
        return this.procedencia;
    }
    
    public void setProcedencia(String procedencia) {
        this.procedencia = procedencia;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Boolean getFactura() {
        return this.factura;
    }
    
    public void setFactura(Boolean factura) {
        this.factura = factura;
    }
    public BigDecimal getPagar() {
        return this.pagar;
    }
    
    public void setPagar(BigDecimal pagar) {
        this.pagar = pagar;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Integer getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }
    public int getIdProfesion() {
        return this.idProfesion;
    }
    
    public void setIdProfesion(int idProfesion) {
        this.idProfesion = idProfesion;
    }
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public Boolean getAsistio() {
        return this.asistio;
    }
    
    public void setAsistio(Boolean asistio) {
        this.asistio = asistio;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


