package entity;
// Generated 19/05/2017 05:19:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaInscripcion generated by hbm2java
 */
public class CategoriaInscripcion  implements java.io.Serializable {


     private int idCategoria;
     private Congreso congreso;
     private String nombre;
     private String descripcion;
     private Set costos = new HashSet(0);

    public CategoriaInscripcion() {
    }

	
    public CategoriaInscripcion(int idCategoria, Congreso congreso, String nombre, String descripcion) {
        this.idCategoria = idCategoria;
        this.congreso = congreso;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public CategoriaInscripcion(int idCategoria, Congreso congreso, String nombre, String descripcion, Set costos) {
       this.idCategoria = idCategoria;
       this.congreso = congreso;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.costos = costos;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Congreso getCongreso() {
        return this.congreso;
    }
    
    public void setCongreso(Congreso congreso) {
        this.congreso = congreso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getCostos() {
        return this.costos;
    }
    
    public void setCostos(Set costos) {
        this.costos = costos;
    }




}


