package entity;
// Generated 19/05/2017 05:19:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idFactura;
     private Aspirante aspirante;
     private String contribuyente;
     private String rfc;
     private String domicilioFiscal;
     private String colonia;
     private int cp;
     private String poblacion;
     private String localidad;
     private String telefono;
     private String correo;
     private String numeroFactura;
     private int idEstado;
     private int idMunicipio;
     private Date fechaSolicitud;

    public Factura() {
    }

	
    public Factura(int idFactura, Aspirante aspirante, String contribuyente, String rfc, String domicilioFiscal, String colonia, int cp, String poblacion, String localidad, String telefono, String correo, int idEstado, int idMunicipio, Date fechaSolicitud) {
        this.idFactura = idFactura;
        this.aspirante = aspirante;
        this.contribuyente = contribuyente;
        this.rfc = rfc;
        this.domicilioFiscal = domicilioFiscal;
        this.colonia = colonia;
        this.cp = cp;
        this.poblacion = poblacion;
        this.localidad = localidad;
        this.telefono = telefono;
        this.correo = correo;
        this.idEstado = idEstado;
        this.idMunicipio = idMunicipio;
        this.fechaSolicitud = fechaSolicitud;
    }
    public Factura(int idFactura, Aspirante aspirante, String contribuyente, String rfc, String domicilioFiscal, String colonia, int cp, String poblacion, String localidad, String telefono, String correo, String numeroFactura, int idEstado, int idMunicipio, Date fechaSolicitud) {
       this.idFactura = idFactura;
       this.aspirante = aspirante;
       this.contribuyente = contribuyente;
       this.rfc = rfc;
       this.domicilioFiscal = domicilioFiscal;
       this.colonia = colonia;
       this.cp = cp;
       this.poblacion = poblacion;
       this.localidad = localidad;
       this.telefono = telefono;
       this.correo = correo;
       this.numeroFactura = numeroFactura;
       this.idEstado = idEstado;
       this.idMunicipio = idMunicipio;
       this.fechaSolicitud = fechaSolicitud;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public Aspirante getAspirante() {
        return this.aspirante;
    }
    
    public void setAspirante(Aspirante aspirante) {
        this.aspirante = aspirante;
    }
    public String getContribuyente() {
        return this.contribuyente;
    }
    
    public void setContribuyente(String contribuyente) {
        this.contribuyente = contribuyente;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getDomicilioFiscal() {
        return this.domicilioFiscal;
    }
    
    public void setDomicilioFiscal(String domicilioFiscal) {
        this.domicilioFiscal = domicilioFiscal;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }
    
    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }




}


