package entity;
// Generated 19/05/2017 05:19:01 PM by Hibernate Tools 4.3.1



/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private int idMunicipio;
     private Estado estado;
     private String nombre;

    public Municipio() {
    }

    public Municipio(int idMunicipio, Estado estado, String nombre) {
       this.idMunicipio = idMunicipio;
       this.estado = estado;
       this.nombre = nombre;
    }
   
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


