package entity;
// Generated 19/05/2017 05:19:01 PM by Hibernate Tools 4.3.1



/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private int idTema;
     private Congreso congreso;
     private String nombre;
     private String descripcion;
     private Integer cupo;
     private boolean activo;

    public Tema() {
    }

	
    public Tema(int idTema, Congreso congreso, String nombre, String descripcion, boolean activo) {
        this.idTema = idTema;
        this.congreso = congreso;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.activo = activo;
    }
    public Tema(int idTema, Congreso congreso, String nombre, String descripcion, Integer cupo, boolean activo) {
       this.idTema = idTema;
       this.congreso = congreso;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cupo = cupo;
       this.activo = activo;
    }
   
    public int getIdTema() {
        return this.idTema;
    }
    
    public void setIdTema(int idTema) {
        this.idTema = idTema;
    }
    public Congreso getCongreso() {
        return this.congreso;
    }
    
    public void setCongreso(Congreso congreso) {
        this.congreso = congreso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCupo() {
        return this.cupo;
    }
    
    public void setCupo(Integer cupo) {
        this.cupo = cupo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


